import type { Agency } from '../types';

export const defaultAgencyConfig: Agency = {
  id: 'agency-bad-boys',
  slug: 'bad-boys-bail-bonds',
  name: 'Bad Boys Bail Bonds',
  legalName: 'BBBB Bonding Corp',
  productName: 'Bail Bond Recovery OS',
  dashboardTitle: 'Collections Command Center',
  initials: 'BB',
  slogan: 'Because Your Mama Wants You Home!',
  phone: '1.800.BAIL.OUT',
  displayPhone: '1.800.BAIL.OUT',
  supportEmail: 'collections@badboysbailbonds.example',
  timezone: 'America/Los_Angeles',
  branding: {
    primaryColor: '#EAB308',
    primaryLightColor: '#FACC15',
    primaryDarkColor: '#CA8A04',
    dangerColor: '#DC2626',
    accentColor: '#3B82F6',
  },
  labels: {
    commandCenter: 'Command Center',
    accounts: 'Accounts',
    automation: 'AI Automation',
    reports: 'Reports',
    totalReceivables: 'Total Receivables',
    activeRecoveryAccounts: 'Active Recovery Accounts',
    dollarsRecovered: 'Recovered This Month',
    promisesCreated: 'Promises Created',
    promisesKept: 'Promises Kept',
    promisesBroken: 'Promises Broken',
    humanHandoffs: 'Human Handoffs',
    highRiskAccounts: 'High-Risk Accounts',
    doNotContactAccounts: 'Do-Not-Contact Accounts',
  },
  offices: [
    {
      id: 'office-san-jose',
      agencyId: 'agency-bad-boys',
      name: 'San Jose',
      region: 'Bay Area',
      county: 'Santa Clara',
      address: '2847 Story Rd, San Jose, CA 95122',
      phone: '1.800.BAIL.OUT',
      notificationEmail: 'sanjose@badboysbailbonds.example',
    },
    {
      id: 'office-oakland',
      agencyId: 'agency-bad-boys',
      name: 'Oakland',
      region: 'Bay Area',
      county: 'Alameda',
      address: '1920 International Blvd, Oakland, CA 94606',
      phone: '1.800.BAIL.OUT',
      notificationEmail: 'oakland@badboysbailbonds.example',
    },
    {
      id: 'office-redwood-city',
      agencyId: 'agency-bad-boys',
      name: 'Redwood City',
      region: 'Peninsula',
      county: 'San Mateo',
      address: '450 Marshall St, Redwood City, CA 94063',
      phone: '1.800.BAIL.OUT',
      notificationEmail: 'redwoodcity@badboysbailbonds.example',
    },
    {
      id: 'office-los-angeles',
      agencyId: 'agency-bad-boys',
      name: 'Los Angeles',
      region: 'Southern California',
      county: 'Los Angeles',
      address: '1733 W Vernon Ave, Los Angeles, CA 90062',
      phone: '1.800.BAIL.OUT',
      notificationEmail: 'losangeles@badboysbailbonds.example',
    },
    {
      id: 'office-santa-ana',
      agencyId: 'agency-bad-boys',
      name: 'Santa Ana',
      region: 'Southern California',
      county: 'Orange',
      address: '2315 N Tustin Ave, Santa Ana, CA 92705',
      phone: '1.800.BAIL.OUT',
      notificationEmail: 'santaana@badboysbailbonds.example',
    },
    {
      id: 'office-san-diego',
      agencyId: 'agency-bad-boys',
      name: 'San Diego',
      region: 'Southern California',
      county: 'San Diego',
      address: '3902 University Ave, San Diego, CA 92105',
      phone: '1.800.BAIL.OUT',
      notificationEmail: 'sandiego@badboysbailbonds.example',
    },
  ],
};

export const agencyConfig = defaultAgencyConfig;
